repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: "v0.0.254"
  hooks:
    - id: ruff
      args: [ "--fix" ]
- repo: https://github.com/pycqa/isort
  rev: "5.11.5"
  hooks:
    - id: isort
      name: Run isort
      alias: isort .
