services:
  redis:
    image: "redis:alpine"
    expose:
      - 6379
    volumes:
      - redis_data:/data

  elasticsearch:
    image: elasticsearch:7.17.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    depends_on:
      - redis

  kibana:
    image: kibana:7.17.2
    volumes:
      - kibana_data:/usr/share/kibana/data
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  etl:
    platform: linux/amd64
    restart: always
    build:
      context: .
    volumes:
      - .:/app
    command: >
      bash -c "cd /app/netflix_etl
      && python etl.py"
    env_file:
      - $ENV
    depends_on:
      - db_admin
      - redis
      - elasticsearch
      - kibana

  db_admin:
    image: yandexmiddleteamv1/netflix-admin-db:master
    environment:
      - POSTGRES_USER=${NA_DB_USER}
      - POSTGRES_PASSWORD=${NA_DB_PASSWORD}
      - POSTGRES_DB=${NA_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  server:
    platform: linux/amd64
    restart: always
    image: yandexmiddleteamv1/netflix-admin:master
    env_file:
      - $ENV
    ports:
      - "8000:8000"
    depends_on:
      - db_admin

volumes:
  redis_data_api:
  postgres_data:
  redis_data:
  es_data:
  kibana_data:
