services:
  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - .:/app
      - ./conf/postgres/scripts:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  elasticsearch:
    image: elasticsearch:7.17.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    depends_on:
      - redis

  kibana:
    image: kibana:7.17.2
    volumes:
      - kibana_data:/usr/share/kibana/data
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  server:
    platform: linux/amd64
    restart: always
    build:
      context: .
    env_file:
      - $ENV
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      bash -c "cd /app
      && django-cadmin migrate
      && django-cadmin collectstatic --no-input
      && django-cadmin runserver_plus --print-sql 0.0.0.0:8000"
    depends_on:
      - db
      - redis
      - elasticsearch

  etl:
    platform: linux/amd64
    restart: always
    build:
      context: ./scripts/populate_elastic
      dockerfile: ./conf/docker/Dockerfile
    env_file:
      - $ENV
    volumes:
      - .:/app
    command: >
      bash -c "cd /app/scripts/populate_elastic
      && python etl.py"
    depends_on:
      - db
      - redis
      - elasticsearch
      - kibana

volumes:
  postgres_data:
  redis_data:
  es_data:
  kibana_data:
