# Generated by Django 3.2.12 on 2022-02-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_add_certificate_file_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('NS', 'not stated')], default='NS', max_length=2, verbose_name='gender'),
        ),
    ]
