# Generated by Django 3.2.12 on 2022-03-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_person_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
    ]
