# Generated by Django 4.0 on 2022-03-19 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_personfilmwork_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmwork',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
